name: fluffychat
description: Chat with your friends.
publish_to: none
# On version bump also increase the build number for F-Droid
version: 2.0.0+3541

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_links: ^6.3.3
  archive: ^3.4.10
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.11.3
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  cupertino_icons: any
  desktop_drop: ^0.4.4
  desktop_notifications: ^0.6.3
  device_info_plus: ^10.0.1
  dynamic_color: ^1.7.0
  emoji_picker_flutter: ^4.3.0
  emojis: ^0.9.9
  #fcm_shared_isolate: ^0.2.0
  file_picker: ^8.1.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_foreground_task: ^6.1.3
  flutter_highlighter: ^0.1.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_new_badger: ^1.1.1
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.4
  flutter_shortcuts_new: ^2.0.0
  flutter_typeahead: ## Custom fork from flutter_typeahead since the package is not maintain well.
    git:
      url: https://github.com/famedly/flutter_typeahead.git
      ref: main
  flutter_vodozemac: ^0.2.2
  flutter_web_auth_2: ^3.1.1 # Version 4 blocked by https://github.com/MixinNetwork/flutter-plugins/issues/379
  flutter_webrtc: ^0.12.9
  geolocator: ^13.0.1
  go_router: ^15.1.2
  handy_window: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: any
  just_audio: ^0.9.39
  latlong2: ^0.9.1
  linkify: ^5.0.0
  matrix: ^1.0.1
  mime: ^1.0.6
  native_imaging: ^0.2.0
  opus_caf_converter_dart: ^1.0.1
  package_info_plus: ^8.0.2
  pasteboard: ^0.2.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  pretty_qr_code: ^3.2.1
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_image: ^1.0.0
  receive_sharing_intent: ^1.8.1
  record: ^6.0.0
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.2.0 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqlcipher_flutter_libs: ^0.6.1
  swipe_to_action: ^0.3.0
  tor_detector_web: ^1.1.0
  unifiedpush: ^5.0.1
  unifiedpush_ui: ^0.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  video_compress: ^3.1.4
  video_player: ^2.9.5
  wakelock_plus: ^1.2.2
  webrtc_interface: ^1.0.13

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  license_checker: ^1.6.0
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

import_sorter:
  ignored_files: # Optional, defaults to []
    - \/lib\/l10n

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/vodozemac/

msix_config:
  display_name: FluffyChat
  publisher_display_name: FluffyChat
  publisher: CN=FluffyChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: chat.fluffy.fluffychat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: fluffychat.im, matrix.to
  execution_alias: fluffychat
  sign_msix: false
  install_certificate: false

dependency_overrides:
  # https://github.com/juliansteenbakker/flutter_secure_storage/issues/920
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      ref: patch-2
      path: flutter_secure_storage_linux
  flutter_secure_storage_platform_interface: 2.0.0
  # https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/155
  flutter_web_auth_2:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth_2.git
      ref: 3.x-without-v1
      path: flutter_web_auth_2
  win32: 5.5.3
