name: fluffychat
# #Pangea
# description: Chat with your friends.
description: Learn a language while texting your friends.
# !!!!!! flutter version: 3.16.9 !!!!!!
# Pangea#
publish_to: none
# On version bump also increase the build number for F-Droid
version: 4.1.9+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_links: ^6.3.3
  archive: ^3.4.10
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.8.1
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  cupertino_icons: any
  # #Pangea
  # desktop_drop: ^0.4.4
  # Pangea#
  desktop_notifications: ^0.6.3
  device_info_plus: ^10.0.1
  diacritic: ^0.1.6
  dynamic_color: ^1.7.0
  emoji_picker_flutter: ^3.1.0
  emojis: ^0.9.9
  #fcm_shared_isolate: ^0.2.0
  file_picker: ^8.1.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_foreground_task: ^6.1.3
  flutter_highlighter: ^0.1.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_new_badger: ^1.1.1
  flutter_olm: 2.0.0
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.3
  flutter_shortcuts_new: ^2.0.0
  flutter_typeahead: ## Custom fork from flutter_typeahead since the package is not maintain well.
    git:
      url: https://github.com/famedly/flutter_typeahead.git
      ref: main
  flutter_web_auth_2: ^3.1.1 # Version 4 blocked by https://github.com/MixinNetwork/flutter-plugins/issues/379
  flutter_webrtc: ^0.12.9
  geolocator: ^13.0.1
  go_router: ^14.8.1
  handy_window: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.1.0
  intl: any
  just_audio: ^0.9.39
  latlong2: ^0.9.1
  linkify: ^5.0.0
  # #Pangea
  matrix:
    git:
      url: https://github.com/pangeachat/matrix-dart-sdk.git # repo
      ref: disable-space-hierarchy-cache # branch
  # matrix: ^0.38.1
  # Pangea#
  mime: ^1.0.6
  native_imaging: ^0.2.0
  opus_caf_converter_dart: ^1.0.1
  package_info_plus: ^8.1.1
  pasteboard: ^0.2.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.4.0
  pretty_qr_code: ^3.2.1
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_image: ^1.0.0
  receive_sharing_intent: ^1.8.1
  record: ^5.1.2
  scroll_to_index: ^3.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.2.0 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqlcipher_flutter_libs: ^0.6.1
  swipe_to_action: ^0.3.0
  tor_detector_web: ^1.1.0
  unifiedpush: ^5.0.1
  unifiedpush_ui: ^0.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  video_compress: ^3.1.4
  video_player: ^2.9.2
  wakelock_plus: ^1.2.2
  webrtc_interface: ^1.0.13
  # #Pangea
  android_intent_plus: ^5.2.0
  app_settings: ^6.1.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  characters: ^1.2.0
  country_picker: ^2.0.25
  csv: ^6.0.0
  dropdown_button2: ^2.3.9
  excel: ^4.0.6
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.1.5
  flutter_dotenv: ^5.1.0
  fcm_shared_isolate:
    path: pangea_packages/fcm_shared_isolate
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  in_app_purchase: ^3.2.1
  jwt_decode: ^0.3.1
  material_symbols_icons: ^4.2741.0
  open_file: ^3.3.2
  purchases_flutter: ^8.5.1
  sentry_flutter: ^8.13.2
  shimmer: ^3.0.0
  rive: 0.11.11
  text_to_speech:
    git: https://github.com/pangeachat/text_to_speech.git
  flutter_tts: ^4.2.0
  # Pangea#

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  license_checker: ^1.6.0
  msix: ^3.6.2
  pedantic: ^1.11.0
  sentry_dart_plugin: ^1.0.0
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    # #Pangea
    # uncomment this to enable mobile builds
    # causes error with github actions
    # - .env
    # - assets/.env
    - assets/pangea/
    - assets/pangea/bot_faces/
    # Pangea#
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 600
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 600
          style: italic
    - family: UbuntuMono
      fonts:
        - asset: fonts/Ubuntu/UbuntuMono-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    # #Pangea
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata/Inconsolata-Light.ttf
          style: italic
        - asset: fonts/Inconsolata/Inconsolata-Bold.ttf
          weight: 700
    # Pangea#

msix_config:
  display_name: FluffyChat
  publisher_display_name: FluffyChat
  publisher: CN=FluffyChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  # #Pangea
  # identity_name: chat.fluffy.fluffychat
  identity_name: com.talktolearn.chat
  # Pangea#
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: fluffychat.im, matrix.to
  execution_alias: fluffychat
  sign_msix: false
  install_certificate: false

dependency_overrides:
  # https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/155
  flutter_web_auth_2:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth_2.git
      ref: 3.x-without-v1
      path: flutter_web_auth_2
  win32: 5.5.3
