name: fluffychat
description: Chat with your friends.
publish_to: none
# On version bump please also increase:
# 1. The build number (for F-Droid)
# 2. The version in /snap/snapcraft.yaml
version: 2.3.0+3545

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.1.1
  app_links: ^6.4.1
  archive: ^4.0.7
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.13.0
  collection: ^1.18.0
  cross_file: ^0.3.5
  cupertino_icons: any
  desktop_drop: ^0.7.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^12.2.0
  dynamic_color: ^1.8.1
  emoji_picker_flutter: ^4.3.0
  file_picker: ^10.3.6
  file_selector: ^1.0.4
  flutter:
    sdk: flutter
  flutter_foreground_task: ^9.1.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_new_badger: ^1.1.1
  flutter_secure_storage: ^9.2.4
  flutter_shortcuts_new: ^2.0.0
  flutter_vodozemac: ^0.4.1
  flutter_web_auth_2: ^4.1.0
  flutter_webrtc: ^1.2.0
  geolocator: ^14.0.2
  go_router: ^17.0.0
  handy_window: ^0.4.0
  highlight: ^0.7.0
  html: ^0.15.4
  http: ^1.6.0
  image: ^4.1.7
  image_picker: ^1.2.1
  intl: any
  just_audio: ^0.10.5
  latlong2: ^0.9.1
  linkify: ^5.0.0
  matrix: ^4.0.0
  mime: ^2.0.0
  native_imaging: ^0.2.0
  opus_caf_converter_dart: ^1.0.1
  package_info_plus: ^8.3.1
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  pretty_qr_code: ^3.5.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner_plus: ^2.0.14
  qr_image: ^1.0.0
  receive_sharing_intent: ^1.8.1
  record: ^6.1.2
  scroll_to_index: ^3.0.1
  share_plus: ^12.0.1
  shared_preferences: ^2.2.0 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  sqflite_common_ffi: ^2.3.6
  sqlcipher_flutter_libs: ^0.6.8
  swipe_to_action: ^0.3.0
  unifiedpush: ^6.2.0
  unifiedpush_ui: ^0.2.0
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  video_compress: ^3.1.4
  video_player: ^2.10.1
  wakelock_plus: ^1.3.3
  webrtc_interface: ^1.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  license_checker: ^1.6.0
  translations_cleaner: ^0.0.5

import_sorter:
  ignored_files: # Optional, defaults to []
    - \/lib\/l10n

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/vodozemac/

# Guidelines for adding a dependency override:
# 1. Don't do it if you can avoid it or fix it upstream in a manageable time
# 2. Always link an (upstream?) issue
# 3. Explain how and when this can be removed (overrides must be temporarily)
dependency_overrides:
