name: fluffychat
description: Chat with your friends.
publish_to: none
version: 1.5.0+2323

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.5.1
  adaptive_theme: ^3.0.0
  animations: ^2.0.2
  blurhash_dart: ^1.1.0
  cached_network_image: ^3.2.0
  callkeep: ^0.3.2
  chewie: ^1.2.2
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^2.2.0
  cupertino_icons: any
  desktop_drop: ^0.3.2
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^4.0.0
  dynamic_color: ^1.2.2
  email_validator: ^2.0.1
  emoji_picker_flutter: ^1.1.2
  encrypt: ^5.0.1
  #fcm_shared_isolate: ^0.1.0
  file_picker_cross: ^4.6.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_app_lock: ^2.0.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^1.1.0
  flutter_matrix_html: ^1.1.0
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  flutter_ringtone_player: ^3.1.1
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  flutter_svg: ^0.22.0
  flutter_typeahead: ^4.0.0
  flutter_web_auth: ^0.4.0
  flutter_webrtc: ^0.8.7
  future_loading_dialog: ^0.2.3
  geolocator: ^7.6.2
  hive_flutter: ^1.1.0
  image: ^3.1.1
  image_picker: ^0.8.4+8
  intl: any
  just_audio: ^0.9.20
  keyboard_shortcuts: ^0.1.4
  localstorage: ^4.0.0+1
  lottie: ^1.2.2
  matrix: ^0.10.1
  matrix_homeserver_recommendations: ^0.2.0
  matrix_link_text: ^1.0.2
  native_imaging:
    git: https://gitlab.com/famedly/company/frontend/libraries/native_imaging.git
  package_info_plus: ^1.3.0
  path_provider: ^2.0.9
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  record: ^4.1.1
  scroll_to_index: ^3.0.1
  sentry: ^6.3.0
  share_plus: ^4.0.9
  shared_preferences: ^2.0.13
  slugify: ^2.0.0
  snapping_sheet: ^3.1.0
  swipe_to_action: ^0.2.0
  uni_links: ^0.5.1
  unifiedpush: ^4.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
  video_compress: ^3.1.0
  video_player: ^2.2.18
  vrouter: ^1.2.0+21
  wakelock: ^0.6.1+1

dev_dependencies:
  dart_code_metrics: ^4.10.1
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  http: ^0.13.4
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

dependency_overrides:
  # Necessary for webRTC on web.
  # Fix for stream fallback for unsupported browsers:
  # https://github.com/fluttercommunity/plus_plugins/pull/746
  # Upstream pull request: https://github.com/fluttercommunity/plus_plugins/pull/746
  connectivity_plus_web:
    git:
      url: https://github.com/TheOneWithTheBraid/plus_plugins.git
      ref: a04401cb48abe92d138c0e9288b360739994a9e9
      path: packages/connectivity_plus/connectivity_plus_web
  dbus: ^0.7.1
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
  provider: 5.0.0
  # For Flutter 3.0.0 compatibility
  # https://github.com/juliuscanute/qr_code_scanner/issues/532
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  # wating for `Listenable` implementation
  # Upstream pull request: https://github.com/AdamJonsson/snapping_sheet/pull/84
  snapping_sheet:
    git:
      url: https://github.com/TheOneWithTheBraid/snapping_sheet.git
      ref: listenable
  #matrix:
  #  path: ../famedlysdk/
