name: fluffychat
description: Chat with your friends.
publish_to: none
version: 0.26.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: main

  unifiedpush:
#    path: /home/sorunome/repos/gotify/flutter_unified_push
    git:
      url: https://github.com/UnifiedPush/flutter-connector.git
      ref: main

  localstorage: ^3.0.6+9
  file_picker_cross: 4.2.2
  image_picker: ^0.6.7+21
  url_launcher: ^5.7.10
  cached_network_image: ^2.5.0
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.3
  adaptive_page_layout: ^0.1.6
  provider: ^4.3.3
  adaptive_theme: ^1.1.0
  # desktop_notifications: ^0.0.0-dev.4  // Currently blocked by: https://github.com/canonical/desktop_notifications.dart/issues/5
  matrix_link_text: ^0.3.2
  path_provider: ^1.6.27
  android_path_provider: ^0.1.1
  permission_handler: ^5.0.1+1
  webview_flutter: ^1.0.7
  share: ^0.6.5+4
  flutter_secure_storage: ^3.3.5
  http: ^0.12.2
  universal_html: ^1.2.4
  receive_sharing_intent:
    # see https://github.com/KasemJaffer/receive_sharing_intent/pull/115
    git:
      url: https://github.com/radvansky-tomas/receive_sharing_intent.git
      ref: 107ea4ae3c3da15be4e6d3337623b69cc2e04c68
  flutter_slidable: ^0.5.7
  flutter_sound_lite: ^7.5.3+1
  open_file: ^3.0.3
  mime_type: ^0.3.2
  flushbar: ^1.10.4
  adaptive_dialog: ^0.9.3
  flutter_matrix_html: ^0.2.0
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  sqlite3: ^0.1.8
  random_string: ^2.1.0
  flutter_typeahead: ^2.0.0
  flutter_olm: ^1.0.1
  intl: any
  circular_check_box: ^1.0.4
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.3.2+2 # Still used to obtain the database location
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  flutter_blurhash: ^0.5.0
  sentry: ">=3.0.0 <4.0.0"
  scroll_to_index: ^1.0.6
  swipe_to_action: ^0.1.0
  flutter_svg: 0.19.1 # Because fluffychat depends on flutter_svg >=0.19.2 which requires Flutter SDK version >=1.24.0-6.0.pre <2.0.0, version solving failed.
  flutter_cache_manager: ^2.1.1
  open_noti_settings: ^0.0.4
  emoji_picker: ^0.1.0
  future_loading_dialog: ^0.1.2
  package_info: ^0.4.3+2
  flutter_app_lock: ^1.4.0+1
  flutter_screen_lock: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  dapackages: ^1.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
        - asset: fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
