name: fluffychat
description: Chat with your friends.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.14.0+40

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: b8c6decafc52cbf5c09288c6c6dde62b62ae978f

  localstorage: ^3.0.1+4
  bubble: ^1.1.9+1
  memoryfilepicker: ^0.1.1
  flutter_speed_dial: ^1.2.5
  url_launcher: ^5.4.1
  url_launcher_web: ^0.1.0
  sqflite: ^1.2.0
  flutter_advanced_networkimage: any
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.3
  link_text: ^0.1.1
  path_provider: ^1.5.1
  webview_flutter: ^0.3.19+9
  share: ^0.6.3+5
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+4
  universal_html: ^1.1.12
  receive_sharing_intent: ^1.3.3
  flutter_slidable: ^0.5.4
  photo_view: ^0.9.2
  flutter_sound: ^2.1.1
  open_file: ^3.0.1
  mime_type: ^0.3.0
  bot_toast: ^3.0.0
  flutter_matrix_html: ^0.1.0
  moor: ^3.0.2
  random_string: ^2.0.1
  flutter_typeahead: ^1.8.1

  intl: ^0.16.0
  intl_translation: ^0.17.9
  flutter_localizations:
    sdk: flutter

  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"
  pedantic: ^1.9.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/js/
    - assets/js/package/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
