name: Matrix Notification

on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Matrix Notification
        env:
          MATRIX_URL: https://matrix.janian.de/_matrix/client/v3/rooms/${{ secrets.MATRIX_MANAGEMENT_ROOM }}/send/m.room.message
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            PAYLOAD="{\"msgtype\": \"m.notice\", \"body\": \"New Issue from ${{ github.event.issue.user.login }}\\n${{ github.event.issue.title }}\\n\\n${{ github.event.issue.body }}\\n\\nURL: ${{ github.event.issue.html_url }}\"}"
          elif [ "${{ github.event.action }}" == "created" ]; then
            PAYLOAD="{\"msgtype\": \"m.notice\", \"body\": \"New Comment from ${{ github.event.comment.user.login }}\\n\\n${{ github.event.comment.body }}\\n\\nURL: ${{ github.event.comment.html_url }}\"}"
          fi
          curl -X POST -H "Authorization: Bearer ${{ secrets.MATRIX_BOT_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               $MATRIX_URL
